### ISSUE TITLE
Zjpm: No canonical requirement for high bits in bare or M-mode

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#20]
2.1 says
"For untranslated addresses (i.e., for Bare and M-mode) canonicity
requirement is for the high bits to be all zeros."

I can't find in the riscv base spec, if there is any requirement of canonicity on high bits in bare or M-mode. 
I don't think there is concept of high bit in Bare or M-mode. If there is, please provide a reference to it or correct the text in spec.

**Comment by martinmaas** [comment]
Addressed in fd7220807e1405ba9b5de38d9d4ac26e73312128 (Chapter 2)
