### ISSUE TITLE
Zjpm: VBITS definition

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#21]
Current VBITS is defined as
"VBITS: The bits within an address that affect which memory is addressed."

I think it would be more appropriate to define as

"VBITS: If virtual memory is enabled, bits of an address which are used to index into page tables"

**Comment by martinmaas** [comment]
Addressed in fd7220807e1405ba9b5de38d9d4ac26e73312128 (Section 2.1)
