### ISSUE TITLE
Zjpm: Differences in ignore transformation and sign extension when paging is enabled v/s not enabled

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#22]
Ignore transformation is explained mainly from perspective when paging is enabled.

When paging is not enabled (or bare mode), ignore transformation still apply?
I believe sign extension exist to accommodate negative kernel addresses (which is function of paging)

In case of M mode or bare mode, there is no paging and thus a sign extended address may fault (may not be even required)
Is the behavior same (of sign extension) when paging doesn't exist ?

**Comment by martinmaas** [comment]
Addressed in fd7220807e1405ba9b5de38d9d4ac26e73312128 (Sections 2.1 and 2.4)

**Comment by martinmaas** [comment]
The new version of the spec further clarifies this – now, virtual addresses are using sign extension and physical addresses are using zero extension (Section 2.2). Section 2.3 has examples of both. Physically addressed environments therefore no longer have to reason about NVBITS and VBITS.

I will close this issue for now – please feel free to reopen if there are still concerns about the latest version.
