### ISSUE TITLE
Zjpm: Clarification on HLV/HSV instructions

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#25]
H extension defines HLV/HSV instructions to allow hypervisor perform loads/store from HS (or even HU) mode as if that access had been done from V mode (i.e. using guest paging structures and applying G stage translations on them). 

Philosophically, pointer masking forms the basis for other technologies like memory tagging, sandboxing, etc and thus it's not actually  meaningful to apply pointer masking on HLV/HSV accesses to guest virtual addresses.

Spec should define if pointer masking applies to such accesses or not (if guest had pointer masking enabled).

I would prefer not to apply pointer masking on HLV/HSV originated accesses.

**Comment by martinmaas** [comment]
Addressed in fd7220807e1405ba9b5de38d9d4ac26e73312128 (Section 2.6)
