### ISSUE TITLE
Zjpm: Addresses reported in CSRs (stval, sepc) hold which addresses?

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#26]
Once PM is enabled, spec must define which values (pre-transformed address, address after masking out bits or ignore transformation address) go into CSRs (sepc, stval on PF) which report addresses to higher priv mode.

Future extensions (like MTE, etc) might fault on mismatches and depending on how fault definition is done, this information will be needed to resolve such faults.

**Comment by martinmaas** [comment]
Addressed in fd7220807e1405ba9b5de38d9d4ac26e73312128 (Section 2.6)

**Comment by martinmaas** [comment]
The latest version of the spec (75e6aa4) now explicitly defines that hardware writes to a CSR store the transformed address (e.g., in the epc and stval cases listed above). On the other hand, software writes store the original address.
