### ISSUE TITLE
Zjpm: PM for instruction fetch

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#30]
Opening this issue for discussion.

Current spec defines an option for pointer masking for instruction fetch. 
I had been thinking and was wondering that do we need pointer masking for instruction fetch?

From sandbox use case perspective, having a cfi and data pointer masking should be good enough to implement sandboxes.
Thoughts?

**Comment by martinmaas** [comment]
Pointer masking no longer applies to instruction fetch, as per request from the architecture review committee and discussions in the J Extension group meetings. Future versions of pointer masking may re-introduce this feature.
