### ISSUE TITLE
Zjpm: formatting: too high column widths per line

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-j-extension#31]
Column widths are way too high for each line.
github is probably wrapping them around certain column width but new lines are coming at high column numbers.

It's difficult to create PRs with such high column width. It'll nice to have column width for each line to be max at 100.

```
 debug@debug$ awk 'length>max{max=length}END{print max}' zjpm/introduction.adoc 
486
```

**Comment by martinmaas** [comment]
I think this is, to a certain extent, a matter of preference and I have found the opposite to be the case (my editor wraps paragraphs and when making changes to a paragraph that is split into multiple lines, it makes the diff very difficult to read when a small change causes the line breaks to end up in different places.

This may be a good topic for RVI to standardize at some point, but for now, I would personally prefer to leave it as is. I will leave this issue open for now, in case there is a lot of demand for making this change from the group.
