### ISSUE TITLE
Zjpm: Clarification on M-mode accesses with MPRV=1

### ISSUE THREAD

**Issue by abrestic-rivos** [riscv/riscv-j-extension#32]
If a memory access is made form M-mode with MPRV=1 and MPP set to a privilege mode with pointer masking enabled, is PM applied for that access? I would expect "yes" since MPRV modifies the privilege level at which loads and stores execute, but it would be good to call this out explicitly in the spec.

**Comment by martinmaas** [comment]
The answer is yes, and the latest version of the spec (75e6aa4) now explicitly calls this out in Section 2.6.
