### ISSUE TITLE
Zjpm: Value of N in M-mode

### ISSUE THREAD

**Issue by abrestic-rivos** [riscv/riscv-j-extension#33]
For the purposes of determining N, I'm assuming M-mode should be equivalent to the BARE case -- i.e. 16 if Zjpmbare16 is present and 0 otherwise. Can we be explicit about this in the spec?

**Comment by martinmaas** [comment]
As of the latest version (75e6aa4), Zjpm no longer defines the value of N and instead defines N to be implementation-specific (Section 2.4). Profiles may constrain N for different privilege modes and address translation modes, including Bare and M-mode. As such, if a profile wishes to define that N be the same in both cases, it can do so.
