### ISSUE TITLE
The CSR Address of upm/spm/vspm/mpm

### ISSUE THREAD

**Issue by tianshi-xty** [riscv/riscv-j-extension#38]
Hi，

I'm reading the "RISC-V Pointer Masking Version 0.4 12/2022", but I don't find the csr address of  mpm/spm/vspm/upm in the spec, am I missing something? And where can I get the csr address?

Thanks,
Tianyi

**Comment by martinmaas** [comment]
The CSR addresses will be assigned once the spec has cleared architecture review. We will update the document at that point. Please note that until then, the spec may still change.
