### ISSUE TITLE
What's the difference between the RISCV-J-extension and MCJIT

### ISSUE THREAD

**Issue by WilliamWangPeng** [riscv/riscv-j-extension#4]
Hi dear everyone,
    The new proposal  RISCV-J-extension stands for the role of JIT compiling as the README.md says, but as far as I know, there are JIT, MCJIT and OrcJIT [1], what's your advantages for taking placing of them?

[1] https://hackage.haskell.org/package/llvm-hs-6.3.0/docs/LLVM-OrcJIT.html#g:1 

Best Regards
Many thanks
William

**Comment by martinmaas** [comment]
The J Extension group does not replace any specific JIT but instead is working on RISC-V instruction set standards that are related to better supporting JIT compilers, interpreters, etc. Specifically, the group is currently developing two standards: pointer masking and instruction/data consistency.
