### ISSUE TITLE
Zjpm: Request rename Smjpmbare16

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-j-extension#43]
Does it possible to rename that to Smjpmbare16b? Extension name end with number is hard to parsing for SW, it will cause confusion when it append with version, e.g. `Smjpmbare16` with version `0.5` -> `Smjpmbare160p5`

Ref: https://github.com/riscv/riscv-isa-manual/pull/718

**Comment by martinmaas** [comment]
As of the latest version 0.6.1 (75e6aa4), this extension is now named Smjpm, as per feedback from the architecture review committee.
