### ISSUE TITLE
Comments on Pointer Masking spec, Version 0.6.1, 08/2023

### ISSUE THREAD

**Issue by deanliberty5** [riscv/riscv-j-extension#44]
Suggested changes (mostly editorial):
-     Chapter 1:  Change "the tag stored in the masked bits is compared" to "the tag stored in the masked bits can be compared".
-     Chapter 1:  In the sentence "If implemented in software, pointer masking still provides performance benefits since all non-checked accesses do not need to transform the address before every memory access.", remove "all".
-     Chapter 1:  In the sentence "If implemented in software, pointer masking still provides performance benefits since all non-checked accesses do not need to transform the address before every memory access.", are you just trying to say that Pointer Masking aids software based tag checking by alleviating software from removing the tag?
-     Section 2.1, Effective address:  "A load/store effective addresses" should be "A load/store effective address" (singular).
-     Section 2.1, Masked bits:  The parenthetical phrase "(we will use N consistently throughout this document to refer to this parameter)" should be a separate, non-parenthetical sentence.
-     Section 2.1, Transformed address:  Append "to remove the masked bits" to the sentence.
-     Section 2.1, Address validity:  Change "For an address to be valid" to "For a virtual address to be valid" and remove the parenthetical phrase "(for virtual addresses)" from the end of the sentence.
-     Section 2.2:  "If N is smaller or equal" should be "If N is less than or equal".
-     Section 2.3:  "Table 1 shows an example of address translation" should be "Table 1 shows an example of transformation on a virtual address".
-     Section 2.3, Table 1, "Effective Address" should say "Virtual address with tag bits set".
-     Somewhere you should say that "N+1st bit from the top" is equivalent to "Bit XLEN-N.  For example, for Sv57 and N=7, this is bit 57."  That way we are consistent with numbering bits from LSB to MSB.
-     Section 2.3, Table 1, "Transformed address" should say "Transformed virtual address".

**Comment by martinmaas** [comment]
Thanks for the comments! Most of the feedback is now incorporated into the latest draft. Please find some additional replies below:

> Chapter 1:  In the sentence "If implemented in software, pointer masking still provides performance benefits since all non-checked accesses do not need to transform the address before every memory access.", are you just trying to say that Pointer Masking aids software based tag checking by alleviating software from removing the tag?

Yes, exactly.

> Section 2.1, Transformed address:  Append "to remove the masked bits" to the sentence.

They are not necessarily removed (since it is sign extension, they may be overwritten with 1's as well). I think defining this in terms of the ignore transformation may be clearer, although I have no strong opinion either way.

> Section 2.3, Table 1, "Effective Address" should say "Virtual address with tag bits set".

I think both are correct, but in my view, saying effective address helps highlight further that the transformation is directly applied to the address produced by the instruction.
