### ISSUE TITLE
Current spec (v0.75) uses inconsistent names for M-mode extension

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv/riscv-j-extension#57]
I see Smpm in section 2.7 and but Smmpm in Section 3.3 and elsewhere. I'm guessing Smpm in section 2.7 is a typo.

**Comment by martinmaas** [comment]
Thanks for catching this; it's indeed a typo. I will update this in the next revision.

**Comment by martinmaas** [comment]
This is now fixed as of d6f29a6.
