### ISSUE TITLE
Question Regarding Pointer Masking Extension Implementation in RISC-V Sail

### ISSUE THREAD

**Issue by HAMZA-AFZAL404** [riscv/riscv-j-extension#62]
Hi,

I just  have few more questions regarding its implementation.

1. In machine mode or bare mode, what determines the number of masked bits? Are they dependent on the PMM bits in the `mseccfg` register?

2. If not, how is the number of masked bits determined in Bare mode?

Any guidance or references would be greatly appreciated. Thank you in advance for your time and assistance.

**Comment by martinmaas** [comment]
That's correct, the number of masked bits is determined by the PMM bits in the mseccfg register (i.e., 7 or 16).

**Comment by martinmaas** [comment]
(Closing this for now, please feel free to re-open if there are additional questions.)
