### ISSUE TITLE
PMLEN=16 with Sv57

### ISSUE THREAD

**Issue by jiahzhang** [riscv/riscv-j-extension#65]
Is it allowed for Sv57 to be used with PMLEN=16? The transformed address given in section 2.2 only defines the new effective address in terms of XLEN and PMLEN.

**Comment by martinmaas** [comment]
Yes, it is allowed if PMLEN=16 is supported by the hardware. However, it is not expected to be mandatory in the profiles, and so it may not be supported on all implementations. The transformation itself is independent of the address translation mode (i.e., Sv57, Sv48, etc.).

**Comment by jiahzhang** [comment]
Thanks
