### ISSUE TITLE
Review comment: clarification with interaction with DMA

### ISSUE THREAD

**Issue by robertlipe** [riscv/riscv-j-extension#69]
Most DMA controllers like to deal with physical addresses. I suppose on-die DMAC that have access to the "other side" of the MMU might deal in virtual addresses, but those seem pretty rare these days.

Is it expected that hardware DMACs will ignore all of these address tags completely and deal strictly in the lower bit, actually defined addresses in a dma_addr_t? Should they (and the code that manipulates them) generally ignore the PMM bits totally and (continue to?) strip off all those tags?

My read is that code like sg_dma_address and others that convert virts to phys and always strip those bits, whether PMLEN=XLEN-57,  PMLEN=XLEN-48, or PMLEN=XLEN-0. 

It might be nice to imagine a DMAC being expected to crack open an address to see if the phys is actually associated with correctly attributed/owned VAs and PAs, but that seems way out of scope with what's possible with the definitions here.

Is it perhaps worth a sentence or to to describe how pointer tagging and masking is expected to be handled by DMA controllers and associated code?

Thank you.

**Comment by martinmaas** [comment]
You are correct – pointer masking does indeed not apply to DMA controllers and other devices. It is therefore the responsibility of the kernel to manually untag these addresses. The spec makes this explicit in Section 2.6:

> Pointer masking only applies to accesses generated by instructions on the CPU (including CPU extensions such as an FPU). E.g., it does not apply to accesses generated by page table walks, the IOMMU, or devices.

We could add DMA controllers to the list, although my thinking is that the current language already makes clear that they are included. Let me know what you think!

**Comment by martinmaas** [comment]
The spec has been updated to clarify that pointer masking does not apply to DMA (654a5c4).
