### ISSUE TITLE
what does Supm and Sspm really mean?

### ISSUE THREAD

**Issue by ubc-guy** [riscv/riscv-j-extension#71]
This is the text describing Sspm and Supm:

In addition, the pointer masking standard defines two extensions that describe an execution
environment but have no bearing on hardware implementations. These extensions are intended to
be used in profile specifications.
• Sspm: An extension that indicates that there is pointer-masking support available in supervisor
mode, with some facility provided in the supervisor execution environment to control pointer
masking.
• Supm: An extension that indicates that there is pointer-masking support available in user
mode, with some facility provided in the application execution environment to control pointer
masking.
The precise nature of these facilities is left to the respective execution environment.

What does this really mean? Does it mean these tags are names to be used in profiles to indicate that the higher privilege level as implemented pointer masking? That is, does Ssnpm always imply Supm, where there is no visible change to the U-level profile but it is an acknowledgement that the higher S mode is doing something to the addresses?

Perhaps this can be conveyed in simpler language.

**Comment by SiFiveHolland** [comment]
> What does this really mean? Does it mean these tags are names to be used in profiles to indicate that the higher privilege level has implemented pointer masking?  

Yes. Supm can imply either Ssnpm or Smnpm, depending on which privilege modes are implemented and/or used on that hart.

> That is, does Ssnpm always imply Supm,

No, not if the supervisor software provides no way to enable pointer masking at runtime in the U-mode execution environment.

> where there is no visible change to the U-level profile but it is an acknowledgement that the higher S mode is doing something to the addresses?

Supm is certainly a visible change to the U-level profile; it means it is possible to have pointer masking enabled while executing in U-mode.

**Comment by martinmaas** [comment]
+1 to Samuel's description.

> What does this really mean? Does it mean these tags are names to be used in profiles to indicate that the higher privilege level as implemented pointer masking? That is, does Ssnpm always imply Supm, where there is no visible change to the U-level profile but it is an acknowledgement that the higher S mode is doing something to the addresses?

I think this is exactly describing the purpose of these extensions. We can adjust the language if it is currently unclear; are there specific changes that would have made it clearer, in your view?

**Comment by martinmaas** [comment]
The spec has been updated to provide an additional explanation (654a5c4).

**Comment by docularxu** [comment]
@SiFiveHolland Hi, Samuel

I recently submitted a patchset that adds the remaining RVA23 Profile v1.0 extensions to the Linux Kernel.

There is currently a discussion regarding whether "Supm" should be added as an extension string in the Device Tree description file (riscv/extensions.yaml).

Since you authored the patches adding "Ssnpm" and "Smnpm," your insight on this would be very helpful. Would you be willing to take a look?

You can find the discussion here: [https://lore.kernel.org/lkml/20260101-prong-carnage-bbb6272e23c1@spud/](https://lore.kernel.org/lkml/20260101-prong-carnage-bbb6272e23c1@spud/ )


Thank you very much.
Best regards,
Guodong Xu

**Comment by SiFiveHolland** [comment]
Thanks for the ping. To summarize [my reply](https://lore.kernel.org/linux-riscv/4ebbe14b-2579-4ba6-808d-d50c24641d04@sifive.com/):

> Supm describes a combination of the hardware capability (Smnpm or Ssnpm), the consumer's privilege level (U), and the software at the next higher privilege level (M or S).
> 
> If the DT is targeting U-mode, then I can see a case for adding Supm to the DT either at runtime or based on the known capabilities of the next-higher-privilege-mode software. So it could make sense to add a binding for Supm. But we still shouldn't add Supm to [the devicetree describing the hardware to privileged system software], because 1) this DT is not targeting U-mode, and 2) this DT is not bound to a particular version of S-mode software.
