### ISSUE TITLE
VS mode access for HLV* and HSV.*  in U mode

### ISSUE THREAD

**Issue by romanheros** [riscv/riscv-j-extension#72]
As the section 3.1. Ssnpm specifies, "_Setting
hstatus.HUPMM enables or disables pointer masking for HLV.* and HSV.* instructions in U-mode,
according to the values in Table 2, when their explicit memory access is performed as though in VUmode_". 

Why the explicit memory access can't be performed as though in VS mode when SPVP is 1?

**Comment by martinmaas** [comment]
We believe that this case is captured by the last sentence of the paragraph:

> Setting henvcfg.PMM enables or disables pointer masking for HLV.* and HSV.* when their explicit memory access is performed as though in VS-mode.
