### ISSUE TITLE
MXR for store instructions

### ISSUE THREAD

**Issue by BiwefC** [riscv/riscv-j-extension#80]
> MPRV and SPVP affect pointer masking as well, causing the pointer masking settings of the effective privilege mode to be applied. When MXR is in effect at the effective privilege mode where explicit memory access is performed, pointer masking does not apply.

In pointer-masking v1.0.0-rc2, MXR will effect whether pointer masking is applied or not. But should store instructions is applied with pointer masking be affected by MXR? If so, why should they be affected?

**Comment by pdonahue-ventana** [comment]
MXR never affects store instructions.  It makes executable pages readable, not writable.  Pointer masking isn't going to change that.

**Comment by BiwefC** [comment]
> MXR never affects store instructions. It makes executable pages readable, not writable. Pointer masking isn't going to change that.

![img_v3_02dp_4e390b0a-6abb-4d30-aa43-cec8a3a7ed0g](https://github.com/user-attachments/assets/0f7488d1-5d3f-4e83-9247-9248d8c68cc1)
But in Spike implementation, pmm directly masked by MXR, regardless of the instruction type. Does this means that there is an issue in Spike's implementation?

**Comment by SiFiveHolland** [comment]
I think the implication is that yes, MXR affects pointer masking for both both loads and stores, but it doesn't really matter because there's no known use case for doing stores with MXR enabled (execute-only pages aren't writable).

**Comment by martinmaas** [comment]
I agree with @SiFiveHolland. I think there is nothing in the spec that says it doesn't apply to stores, but it does not matter.
