### ISSUE TITLE
Questions about hstatus.HUPMM

### ISSUE THREAD

**Issue by sealman-Kuo** [riscv/riscv-j-extension#81]
Hi, I have some questions about hstatus.HUPMM.

The spec states, _"The hypervisor should copy the value written to senvcfg.PMM by the guest to the hstatus.HUPMM field prior to invoking HLV.* or HSV.* instructions in U-mode."_

Is this a mandatory requirement, or just a recommendation? If it is mandatory, then senvcfg.PMM and hstatus.HUPMM would always be equal. Why does VU mode access for HLV* and HSV.* in U mode require adding the hstatus.HUPMM field, but VS mode access for these instructions in U mode can directly use the henvcfg.PMM setting?

**Comment by martinmaas** [comment]
This is only a recommendation how software may manage these registers. A hypervisor is free to ignore this recommendation, but it is unclear how HLV.* and HSV.* instructions would be used in this case.
