### ISSUE TITLE
How to understand this sentence in the PM spec--"Alternatively, an implementation may choose to "waste" TLB capacity by having up to 4 duplicate entries for each page." 

### ISSUE THREAD

**Issue by chara811** [riscv/riscv-j-extension#87]
When vsatp=bare,hgatp=sv48x4,GPA[49:48] =00,01,10 or 11,but we can't see these 2 bits, so there will be 4 duplicate pages.
Can I understand it this way?

**Comment by SiFiveHolland** [comment]
Yes, an implementation making this choice would have a TLB entry for each possible value of GPA[49:48], since an address references the same page regardless of the value of those bits.

**Comment by martinmaas** [comment]
Thanks @SiFiveHolland for responding to the question. I am closing the issue for now – please re-open if there are any follow-ups.
