### ISSUE TITLE
The virtual address (VA) bit extension check failed, a fault needs to be reported, and the VA needs to be written into mtval register. Is it the VA after the PM mask or before the mask?

### ISSUE THREAD

**Issue by chara811** [riscv/riscv-j-extension#88]

**Comment by pdonahue-ventana** [comment]
This question is directly addressed in the spec: https://github.com/riscv/riscv-isa-manual/blob/main/src/zpm.adoc?plain=1#L175

**Comment by martinmaas** [comment]
Thanks @pdonahue-ventana for responding to the question. I am closing the issue for now – please re-open if there are any follow-ups.
